### ISSUE TITLE
Isn't working

### ISSUE THREAD

**Issue by IndubitablyBengt** [DinosParkour/discord-theme#13]
All I see is [this](http://i.imgur.com/ffmaLWn.png)

**Comment by TyroneSWG** [comment]
Same

**Comment by RjGunner111** [comment]
me 3

**Comment by LBManiac** [comment]
me 4
would really like this theme too, looks awesome

**Comment by Link-Hero-of-Hyrule** [comment]
please fix the theme so it works
T-T

**Comment by din0s** [comment]
Apologies for the long delay. This should be fixed now.
