### ISSUE TITLE
Theme breaks at chat and users bar

### ISSUE THREAD

**Issue by DJCharizard** [DinosParkour/discord-theme#4]
![discord](https://cloud.githubusercontent.com/assets/20470589/16864386/49cc7c3e-4a2a-11e6-8183-88b4dc715eb5.PNG)
Skin looked like this earlier.
Now it looks like this.
![capture2](https://cloud.githubusercontent.com/assets/20470589/16864396/5be09ac2-4a2a-11e6-898e-c9268fbdc4bb.PNG)

**Comment by DJCharizard** [comment]
Looks like `.theme-dark .chat{background: transparent;}` just needed to be added in a new line.

**Comment by DinosParkour** [comment]
Screenshot please?

**Comment by din0s** [comment]
Thanks for letting me know! Fixed with 696f08c.
