### ISSUE TITLE
No //META Tag At Begining

### ISSUE THREAD

**Issue by swawesome9598** [DinosParkour/discord-theme#5]
Hi i have been trying to install the nova theme but none of the versions have the //META tag on them so i cant use them please fix thanks.

**Comment by din0s** [comment]
The repo contains the actual CSS code and not the theme file that BetterDiscord requires. Please visit the [releases section](https://github.com/DinosParkour/discord-theme/releases) to find and download the aforementioned files.

**Comment by swawesome9598** [comment]
Thank you!
